version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  "Test":
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          context: vdms-api-client-test-account
